# SPDX-License-Identifier: GPL-2.0
#
# Make file to build device tree binaries for boards based on
# Texas Instruments Inc processors
#
# Copyright (C) 2016-2018 Texas Instruments Incorporated - http://www.ti.com/
# Copyright (C) 2020 TQ Systems
#

DTC_FLAGS += -@

dtb-$(CONFIG_ARCH_K3_AM6_SOC) += am654-mba65xx-p1.dtb  \
				 am654-mba65xx-p2.dtb  \
				 am654-mba65xx-eth-prg0.dtbo \
				 am654-mba65xx-eth-prg1.dtbo \
				 am654-mba65xx-audio.dtbo
