# SPDX-License-Identifier: GPL-2.0
#
# Make file to build device tree binaries for boards based on
# Texas Instruments Inc processors
#
# Copyright (C) 2016-2018 Texas Instruments Incorporated - http://www.ti.com/
# Copyright (C) 2020 TQ Systems
#

DTC_FLAGS += -@

dtb-$(CONFIG_ARCH_K3_AM6_SOC) += tqma654-base-board.dtb  \
				 tqma654-gp.dtbo \
				 tqma654-evm-hdmi.dtbo \
				 tqma654-base-board-jailhouse.dtbo \
				 tqma654-evm-oldi-lcd1evm.dtbo \
				 tqma654-evm-tc358876.dtbo \
				 tqma654-idk.dtbo \
				 tqma654-pcie-usb3.dtbo \
				 tqma654-pcie-usb2.dtbo \
				 tqma654-evm-prupwm.dtbo
